# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC (used for npm publish with Trusted publishing)
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          package-manager-cache: true
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build

      - name: Publish
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --no-git-checks --access public --registry https://registry.npmjs.org

      - name: Publish on GitHub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          pnpm publish --no-git-checks --access restricted --registry https://npm.pkg.github.com
